# Generated by Django 5.2.17 on 2026-09-26 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "waitlist entries",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=12, unique=True)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=20)),
                (
                    "mode",
                    models.CharField(
                        choices=[("in_person", "In person"), ("video", "Video visit")],
                        default="in_person",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("checked_in", "Checked in"),
                            ("in_progress", "In consultation"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        db_index=True,
                        default="booked",
                        max_length=12,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        max_length=200, verbose_name="Main reason for visit"
                    ),
                ),
                ("symptoms", models.TextField(blank=True)),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="Self-reported, 1–10"
                    ),
                ),
                (
                    "symptom_duration",
                    models.CharField(
                        choices=[
                            ("hours", "A few hours"),
                            ("days", "A few days"),
                            ("weeks", "A few weeks"),
                            ("months", "Months or longer"),
                        ],
                        default="days",
                        max_length=10,
                    ),
                ),
                (
                    "urgency",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Routine"),
                            (2, "Needs attention soon"),
                            (3, "Urgent"),
                        ],
                        default=1,
                    ),
                ),
                ("red_flags", models.CharField(blank=True, max_length=300)),
                ("fee", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                        ],
                        default="unpaid",
                        max_length=8,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("queue_number", models.PositiveIntegerField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=200)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
    ]
