# Generated by Django 5.2.17 on 2026-09-26 22:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import records.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.CharField(max_length=200)),
                ("clinical_notes", models.TextField(blank=True)),
                (
                    "advice",
                    models.TextField(blank=True, verbose_name="Advice for the patient"),
                ),
                (
                    "follow_up_in_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "allergy_override",
                    models.BooleanField(
                        default=False,
                        help_text="Doctor confirmed despite an allergy warning",
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        default=records.models._verification_code,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other / prefer not to say"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A−", "A−"),
                            ("B+", "B+"),
                            ("B−", "B−"),
                            ("AB+", "AB+"),
                            ("AB−", "AB−"),
                            ("O+", "O+"),
                            ("O−", "O−"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        help_text="Comma separated, e.g. penicillin, peanuts",
                    ),
                ),
                (
                    "chronic_conditions",
                    models.TextField(blank=True, help_text="Comma separated"),
                ),
                (
                    "current_medications",
                    models.TextField(blank=True, help_text="Comma separated"),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine", models.CharField(max_length=120)),
                ("dosage", models.CharField(help_text="e.g. 500 mg", max_length=60)),
                (
                    "frequency",
                    models.CharField(help_text="e.g. 1-0-1 after meals", max_length=60),
                ),
                ("duration", models.CharField(help_text="e.g. 5 days", max_length=60)),
                ("instructions", models.CharField(blank=True, max_length=200)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="records.consultation",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view_chart", "Viewed health record"),
                            ("consult", "Opened consultation"),
                            ("prescribe", "Issued prescription"),
                            ("vitals", "Recorded vitals"),
                            ("admit", "Admitted to ward"),
                        ],
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=200)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-created_at"],
                        name="records_acc_patient_c3554d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VitalReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "systolic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(260),
                        ],
                        verbose_name="Systolic (mmHg)",
                    ),
                ),
                (
                    "diastolic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(160),
                        ],
                        verbose_name="Diastolic (mmHg)",
                    ),
                ),
                (
                    "heart_rate",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(250),
                        ],
                        verbose_name="Heart rate (bpm)",
                    ),
                ),
                (
                    "glucose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("20")),
                            django.core.validators.MaxValueValidator(Decimal("700")),
                        ],
                        verbose_name="Blood glucose (mg/dL)",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("30")),
                            django.core.validators.MaxValueValidator(Decimal("45")),
                        ],
                        verbose_name="Temperature (°C)",
                    ),
                ),
                (
                    "spo2",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="SpO₂ (%)",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1")),
                            django.core.validators.MaxValueValidator(Decimal("400")),
                        ],
                        verbose_name="Weight (kg)",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-recorded_at"],
                        name="records_vit_patient_c6b4cd_idx",
                    )
                ],
            },
        ),
    ]
