# Generated by Django 5.2.17 on 2026-09-26 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("code", models.CharField(max_length=8, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("icu", "Intensive care"),
                            ("maternity", "Maternity"),
                            ("pediatric", "Pediatric"),
                            ("surgical", "Surgical"),
                            ("emergency", "Emergency"),
                        ],
                        default="general",
                        max_length=12,
                    ),
                ),
                ("floor", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("cleaning", "Needs cleaning"),
                            ("reserved", "Reserved"),
                            ("maintenance", "Out of service"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=12,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="operations.ward",
                    ),
                ),
            ],
            options={
                "ordering": ["ward__code", "label"],
            },
        ),
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                ("admitted_at", models.DateTimeField(auto_now_add=True)),
                ("discharged_at", models.DateTimeField(blank=True, null=True)),
                ("discharge_note", models.CharField(blank=True, max_length=200)),
                (
                    "attending",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admissions",
                        to="clinic.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions",
                        to="operations.bed",
                    ),
                ),
            ],
            options={
                "ordering": ["-admitted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("discharged_at__isnull", True)),
                        fields=("bed",),
                        name="one_active_admission_per_bed",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("discharged_at__isnull", True)),
                        fields=("patient",),
                        name="one_active_admission_per_patient",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="bed",
            constraint=models.UniqueConstraint(
                fields=("ward", "label"), name="uniq_bed_label_per_ward"
            ),
        ),
    ]
